name             'unicorn'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures unicorn'
long_description 'Installs/Configures unicorn'
version          '0.1.0'
