name             'unicorn'
maintainer       'Jimmy Malone'
maintainer_email 'jimmy@girlfriend.com'
license          'All rights reserved'
description      'Installs/Configures unicorn for Opsworks'
long_description 'Installs/Configures unicorn for Opsworks'
version          '0.1.0'
